apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJkVzVqYkdVdFlXeG1aWEk2WjJod1gybEtXWGh3UjI4eVJtWnBaVEZhYjBsd2JEVXlVbkZ6T1V0Q1UxbFJTRFJpTURoSWNRPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
